version: "3.8"

services:
  redis:
    image: "redis:7.4-alpine"
    restart: always
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - internal-network

  app:
    depends_on:
      - redis
    build: .
    ports:
      - "3000:3000"
    restart: always
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
